[project]
name = "edgewise"
version = "0.1.0"
description = ""
authors = [{ name = "Jacopo Massa", email = "jacopomassa97@gmail.com" }]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
ortools = "^9.12.4544"
swiplserver = "^1.0.2"
ray = { extras = ["tune"], version = "^2.44.0" }
pandas = "^2.2.3"
seaborn = "^0.13.2"
ipykernel = "^6.29.5"
pyarrow = "<18"
eclypse = "0.6.19"
prolog-to-networkx = { git = "https://github.com/jacopo-massa/prolog-to-networkx" }


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
